services:
  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      REDIS_PASSWORD: ""
      REDIS_USER: "user"
      REDIS_USER_PASSWORD: ""
    ports:
      - "6380:6379"
    volumes:
      - ./redisdata:/data
  emailsender:
    build:
      dockerfile: services/emailsender/Dockerfile
      context: .
    ports:
      - "8083:8083"
    depends_on:
      - redis